'use client';

import React, { useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';

export default function BulkImportProductsPage() {
  const router = useRouter();
  const [jsonText, setJsonText] = useState('');
  const [parsedPreview, setParsedPreview] = useState<any[]>([]);
  const [parseError, setParseError] = useState('');
  const [importing, setImporting] = useState(false);
  const [importResult, setImportResult] = useState<any>(null);

  // Sample template generator
  const sampleTemplate = [
    {
      name: "15W Magnetic Wireless Car Phone Mount Charger",
      category: "Car Accessories",
      price: 2499,
      originalPrice: 3499,
      image: "car-charger-main.webp",
      images: [
        "car-charger-main.webp",
        "car-charger-angle.webp",
        "car-charger-in-car.webp"
      ],
      description: "Fast 15W Qi-certified magnetic wireless car charger with 360-degree rotation. Secure air vent clip designed for Pakistani road bumps.",
      stock: 30,
      isFeatured: true,
      isTopSelling: true,
      specifications: {
        "Output": "15W / 10W / 7.5W Fast Charge",
        "Material": "ABS + Aluminum Alloy",
        "Compatibility": "iPhone 12-16 & MagSafe Android"
      }
    },
    {
      name: "A11 Pro ANC Wireless Earbuds with Smart Screen Display",
      category: "Mobile Accessories",
      price: 1899,
      originalPrice: 2899,
      image: "a11-pro-main.webp",
      images: [
        "a11-pro-main.webp",
        "a11-pro-case.webp"
      ],
      description: "Active Noise Cancelling TWS Earbuds with smart LCD touch screen charging case. Control music, volume and equalizer directly from the case.",
      stock: 45,
      isFeatured: true,
      isTopSelling: false,
      specifications: {
        "Bluetooth": "V5.4 Ultra Low Latency",
        "Battery Life": "Up to 32 Hours with Case",
        "Features": "Full Color Touch Screen, ANC"
      }
    }
  ];

  const handleJsonChange = (val: string) => {
    setJsonText(val);
    setParseError('');
    setImportResult(null);

    if (!val.trim()) {
      setParsedPreview([]);
      return;
    }

    try {
      const parsed = JSON.parse(val);
      const items = Array.isArray(parsed) ? parsed : parsed.products ? parsed.products : [parsed];
      setParsedPreview(items);
    } catch (e: any) {
      setParseError('Invalid JSON format: ' + e.message);
      setParsedPreview([]);
    }
  };

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = (event) => {
      const content = event.target?.result as string;
      handleJsonChange(content);
    };
    reader.readAsText(file);
  };

  const handleLoadSample = () => {
    handleJsonChange(JSON.stringify(sampleTemplate, null, 2));
  };

  const handleExecuteImport = async () => {
    if (parsedPreview.length === 0) return;

    try {
      setImporting(true);
      setImportResult(null);

      const res = await fetch('/api/products/import', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(parsedPreview),
      });

      const data = await res.json();
      if (data.success) {
        setImportResult({
          success: true,
          message: data.message,
          count: data.count,
        });
      } else {
        setImportResult({
          success: false,
          error: data.error || 'Failed to import products.',
        });
      }
    } catch (err: any) {
      setImportResult({
        success: false,
        error: err.message || 'An unexpected error occurred during import.',
      });
    } finally {
      setImporting(false);
    }
  };

  return (
    <div className="container-fluid py-4" style={{ minHeight: '100vh', background: '#f8fafc' }}>
      <div className="container">
        
        {/* Header */}
        <div className="d-flex flex-wrap align-items-center justify-content-between gap-3 mb-4">
          <div>
            <Link href="/admin/products" className="text-decoration-none text-muted small d-inline-flex align-items-center gap-1 mb-2">
              <i className="fas fa-arrow-left" /> Back to Products
            </Link>
            <h1 className="h3 fw-bold text-dark m-0">📥 Bulk Import Products (AI & JSON)</h1>
            <p className="text-muted small m-0 mt-1">
              Import dozens of products generated by Gemini in 1-Click with automatic categories and gallery resolution.
            </p>
          </div>

          <div className="d-flex gap-2">
            <button
              type="button"
              onClick={handleLoadSample}
              className="btn btn-outline-secondary btn-sm px-3"
            >
              <i className="fas fa-file-code me-1" /> Load Sample JSON
            </button>
            <Link href="/admin/products" className="btn btn-outline-dark btn-sm px-3">
              View Catalog
            </Link>
          </div>
        </div>

        {/* Workflow Info Box */}
        <div className="card border-0 shadow-sm rounded-3 mb-4" style={{ background: '#f0fdf4', borderLeft: '4px solid #16a34a' }}>
          <div className="card-body py-3">
            <div className="d-flex align-items-start gap-3">
              <div className="p-2 bg-success text-white rounded-circle d-flex align-items-center justify-content-center" style={{ width: '36px', height: '36px' }}>
                <i className="fas fa-magic" />
              </div>
              <div className="small text-dark">
                <strong>⚡ Gemini AI Workflow:</strong>
                <ol className="m-0 ps-3 mt-1 text-secondary">
                  <li>Apne product ki photos Gemini ko dein aur hamara format prompt paste karein.</li>
                  <li>Gemini ke banaye hue JSON ko copy karein aur neeche paste karein (ya <code>.json</code> file upload karein).</li>
                  <li>Images ko <code>public/product-imports/</code> folder me rakh dein — system automatically gallery images connect kar dega!</li>
                </ol>
              </div>
            </div>
          </div>
        </div>

        <div className="row g-4">
          
          {/* Left Column: JSON Input & File Upload */}
          <div className="col-lg-6">
            <div className="card border-0 shadow-sm rounded-3 h-100">
              <div className="card-header bg-white py-3 d-flex justify-content-between align-items-center border-bottom">
                <span className="fw-bold text-dark small">Paste or Upload Product JSON</span>
                <label className="btn btn-sm btn-outline-primary m-0 cursor-pointer">
                  <i className="fas fa-upload me-1" /> Upload .JSON File
                  <input type="file" accept=".json" onChange={handleFileUpload} style={{ display: 'none' }} />
                </label>
              </div>
              <div className="card-body p-3">
                <textarea
                  className="form-control font-monospace"
                  rows={16}
                  placeholder={`[\n  {\n    "name": "Product Title",\n    "category": "Car Accessories",\n    "price": 2499,\n    "image": "photo1.webp",\n    "images": ["photo1.webp", "photo2.webp"],\n    "description": "Product details..."\n  }\n]`}
                  value={jsonText}
                  onChange={(e) => handleJsonChange(e.target.value)}
                  style={{ fontSize: '0.82rem', background: '#0f172a', color: '#38bdf8', border: '1px solid #334155' }}
                />

                {parseError && (
                  <div className="alert alert-danger small mt-3 mb-0 py-2 d-flex align-items-center gap-2">
                    <i className="fas fa-exclamation-triangle" /> {parseError}
                  </div>
                )}
              </div>
            </div>
          </div>

          {/* Right Column: Live Parsed Preview & Actions */}
          <div className="col-lg-6">
            <div className="card border-0 shadow-sm rounded-3 h-100 d-flex flex-column">
              <div className="card-header bg-white py-3 d-flex justify-content-between align-items-center border-bottom">
                <span className="fw-bold text-dark small">
                  Live Preview ({parsedPreview.length} Products Detected)
                </span>
                {parsedPreview.length > 0 && (
                  <span className="badge bg-success small px-2 py-1">Ready to Import</span>
                )}
              </div>

              <div className="card-body p-3 flex-grow-1" style={{ maxHeight: '420px', overflowY: 'auto' }}>
                {parsedPreview.length === 0 ? (
                  <div className="text-center py-5 text-muted">
                    <i className="fas fa-boxes fa-3x mb-3 text-secondary opacity-50" />
                    <p className="small m-0">Paste JSON on the left to see the live product preview.</p>
                  </div>
                ) : (
                  <div className="list-group list-group-flush">
                    {parsedPreview.map((item, idx) => (
                      <div key={idx} className="list-group-item px-0 py-2.5 border-bottom">
                        <div className="d-flex justify-content-between align-items-start gap-2">
                          <div>
                            <span className="badge bg-secondary text-light small me-2">#{idx + 1}</span>
                            <strong className="text-dark small">{item.name || 'Untitled Product'}</strong>
                            <div className="text-muted" style={{ fontSize: '0.75rem' }}>
                              Category: <span className="text-primary">{item.category || 'General'}</span> | Stock: {item.stock || 25}
                            </div>
                            <div className="text-muted" style={{ fontSize: '0.72rem' }}>
                              Main Image: <code className="text-dark">{item.image || 'none'}</code> ({item.images?.length || 0} gallery photos)
                            </div>
                          </div>
                          <div className="text-end flex-shrink-0">
                            <span className="fw-bold text-success d-block" style={{ fontSize: '0.9rem' }}>
                              Rs. {Number(item.price || 0).toLocaleString()}
                            </span>
                            {item.originalPrice && (
                              <del className="text-muted" style={{ fontSize: '0.75rem' }}>
                                Rs. {Number(item.originalPrice).toLocaleString()}
                              </del>
                            )}
                          </div>
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </div>

              {/* Status Message */}
              {importResult && (
                <div className={`p-3 border-top ${importResult.success ? 'bg-success text-white' : 'bg-danger text-white'}`}>
                  <div className="d-flex align-items-center justify-content-between">
                    <span className="small fw-bold">
                      {importResult.success ? `🎉 ${importResult.message}` : `❌ ${importResult.error}`}
                    </span>
                    {importResult.success && (
                      <button
                        onClick={() => router.push('/admin/products')}
                        className="btn btn-light btn-sm fw-bold px-3"
                      >
                        View All in Admin ➔
                      </button>
                    )}
                  </div>
                </div>
              )}

              {/* Footer CTA */}
              <div className="card-footer bg-white p-3 border-top">
                <button
                  type="button"
                  onClick={handleExecuteImport}
                  disabled={parsedPreview.length === 0 || importing || !!parseError}
                  className="btn btn-success w-100 py-2.5 fw-bold d-flex align-items-center justify-content-center gap-2 shadow-sm"
                  style={{ background: '#16a34a', border: 'none' }}
                >
                  {importing ? (
                    <>
                      <span className="spinner-border spinner-border-sm" role="status" aria-hidden="true" />
                      Importing Products to Database...
                    </>
                  ) : (
                    <>
                      <i className="fas fa-cloud-upload-alt" />
                      Import {parsedPreview.length} Products to Store
                    </>
                  )}
                </button>
              </div>

            </div>
          </div>

        </div>

      </div>
    </div>
  );
}
