'use client';

import React from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useAdminBulkImport } from '@/hooks/useAdminBulkImport';

export default function BulkImportProductsPage() {
  const router = useRouter();
  const {
    jsonText,
    parsedPreview,
    parseError,
    importing,
    importResult,
    categories,
    categoriesLoading,
    aiPromptModalOpen,
    copiedPrompt,
    copiedJson,
    dynamicTaxonomyText,
    dynamicSampleJsonText,
    fullGeminiPromptText,
    handleJsonChange,
    handleFileUpload,
    handleLoadSample,
    handleLoadAiTemplateIntoEditor,
    handleExecuteImport,
    handleCopyPrompt,
    handleCopyJson,
    setAiPromptModalOpen,
  } = useAdminBulkImport();

  return (
    <div className="container-fluid py-4" style={{ minHeight: '100vh', background: '#f8fafc' }}>
      <div className="container max-w-6xl">
        {/* Header */}
        <div className="d-flex flex-wrap align-items-center justify-content-between gap-3 mb-3">
          <div>
            <Link
              href="/admin/products"
              className="text-decoration-none text-muted small d-inline-flex align-items-center gap-1 mb-2"
            >
              <i className="fas fa-arrow-left" /> Back to Products
            </Link>
            <h1 className="h3 fw-bold text-dark m-0 d-flex align-items-center gap-2">
              <span>📥 Bulk Import Products</span>
              <span
                className="badge bg-primary bg-opacity-10 text-primary border border-primary border-opacity-25"
                style={{ fontSize: '0.75rem', fontWeight: 700 }}
              >
                AI & JSON Engine
              </span>
            </h1>
            <p className="text-muted small m-0 mt-1">
              Import products generated by Gemini in 1-Click with automatic categories, SEO tags, and specs.
            </p>
          </div>

          <div className="d-flex flex-wrap gap-2 align-items-center">
            <button
              type="button"
              onClick={() => setAiPromptModalOpen(true)}
              className="btn btn-primary btn-sm px-3 fw-bold text-white shadow-sm d-flex align-items-center gap-2"
              style={{ background: 'linear-gradient(135deg, var(--pd-primary, #ea580c), #f97316)', border: 'none' }}
            >
              <i className="fas fa-robot" />
              <span>⚡ Gemini AI Prompt Builder</span>
              {!categoriesLoading && (
                <span className="badge bg-white text-dark ms-1" style={{ fontSize: '0.68rem' }}>
                  {categories.length} Categories Live
                </span>
              )}
            </button>

            <button
              type="button"
              onClick={handleLoadSample}
              className="btn btn-outline-secondary btn-sm px-3 fw-bold"
            >
              <i className="fas fa-magic me-1" /> Load Sample JSON
            </button>

            <Link href="/admin/products" className="btn btn-outline-dark btn-sm px-3">
              View Catalog
            </Link>
          </div>
        </div>

        {/* AI Quick Copilot Banner */}
        <div
          className="card border-0 shadow-sm rounded-3 mb-4"
          style={{
            background: 'linear-gradient(135deg, #eff6ff 0%, #f0fdf4 100%)',
            borderLeft: '5px solid var(--pd-primary, #ea580c)',
          }}
        >
          <div className="card-body py-3 px-4">
            <div className="d-flex flex-wrap align-items-center justify-content-between gap-3">
              <div className="d-flex align-items-start gap-3 flex-grow-1" style={{ minWidth: '280px' }}>
                <div
                  className="p-2 text-white rounded-circle d-flex align-items-center justify-content-center flex-shrink-0"
                  style={{ width: '40px', height: '40px', background: 'var(--pd-primary, #ea580c)' }}
                >
                  <i className="fas fa-wand-magic-sparkles" />
                </div>
                <div>
                  <div className="d-flex align-items-center gap-2 flex-wrap">
                    <strong className="text-dark" style={{ fontSize: '0.95rem' }}>
                      Generate Products with Gemini AI (Images & Details)
                    </strong>
                    <span className="badge bg-success bg-opacity-15 text-success small px-2 py-0.5 rounded-pill">
                      SEO Optimized
                    </span>
                  </div>
                  <p className="text-secondary small m-0 mt-1" style={{ lineHeight: '1.45' }}>
                    1. Copy the <strong>Gemini Prompt</strong> below &rarr; 2. Paste in Gemini along with product photos &rarr; 3. Paste the generated JSON here to import!
                  </p>
                </div>
              </div>

              <div className="d-flex gap-2 flex-wrap flex-shrink-0">
                <button
                  type="button"
                  onClick={handleCopyPrompt}
                  className={`btn btn-sm fw-bold px-3 d-flex align-items-center gap-1.5 shadow-sm transition-all ${
                    copiedPrompt ? 'btn-success text-white' : 'btn-dark text-white'
                  }`}
                >
                  <i className={copiedPrompt ? 'fas fa-check' : 'fas fa-copy'} />
                  <span>{copiedPrompt ? '✓ Copied Prompt!' : '📋 Copy Gemini Prompt'}</span>
                </button>

                <button
                  type="button"
                  onClick={() => setAiPromptModalOpen(true)}
                  className="btn btn-outline-primary btn-sm fw-bold px-3"
                >
                  <i className="fas fa-eye me-1" /> View Schema & Categories
                </button>
              </div>
            </div>
          </div>
        </div>

        {/* Main Work Area: JSON Input & Live Preview */}
        <div className="row g-4">
          {/* Left Column: JSON Input & File Upload */}
          <div className="col-lg-6">
            <div className="card border-0 shadow-sm rounded-3 h-100">
              <div className="card-header bg-white py-3 d-flex justify-content-between align-items-center border-bottom">
                <div className="d-flex align-items-center gap-2">
                  <span className="fw-bold text-dark small">Paste or Upload Product JSON</span>
                  {parsedPreview.length > 0 && (
                    <span className="badge bg-success bg-opacity-10 text-success small">
                      {parsedPreview.length} Items
                    </span>
                  )}
                </div>
                <div className="d-flex gap-2">
                  <label className="btn btn-sm btn-outline-primary m-0 cursor-pointer">
                    <i className="fas fa-upload me-1" /> Upload .JSON File
                    <input
                      type="file"
                      accept=".json"
                      onChange={handleFileUpload}
                      style={{ display: 'none' }}
                    />
                  </label>
                </div>
              </div>

              <div className="card-body p-3 d-flex flex-column">
                <textarea
                  className="form-control font-monospace flex-grow-1"
                  rows={18}
                  placeholder={`[\n  {\n    "name": "Product Title",\n    "category": "Car Accessories",\n    "subcategory": "Car Perfumes & Fresheners",\n    "price": 2499,\n    "originalPrice": 3499,\n    "stock": 50,\n    "image": "https://...",\n    "images": ["https://..."],\n    "description": "Product details...",\n    "specifications": { "Material": "Alloy" },\n    "seoTitle": "Title — Buy in Pakistan | PAKODRIVE",\n    "seoDescription": "Buy in Pakistan with COD...",\n    "seoKeywords": "car accessories, online COD"\n  }\n]`}
                  value={jsonText}
                  onChange={(e) => handleJsonChange(e.target.value)}
                  style={{
                    fontSize: '0.82rem',
                    background: '#0f172a',
                    color: '#38bdf8',
                    border: '1px solid #334155',
                    borderRadius: '8px',
                    minHeight: '380px',
                  }}
                />

                {parseError && (
                  <div className="alert alert-danger small mt-3 mb-0 py-2 d-flex align-items-center gap-2">
                    <i className="fas fa-exclamation-triangle flex-shrink-0" />
                    <span>{parseError}</span>
                  </div>
                )}
              </div>
            </div>
          </div>

          {/* Right Column: Live Parsed Preview & Import Action */}
          <div className="col-lg-6">
            <div className="card border-0 shadow-sm rounded-3 h-100 d-flex flex-column">
              <div className="card-header bg-white py-3 d-flex justify-content-between align-items-center border-bottom">
                <span className="fw-bold text-dark small">
                  Live Preview ({parsedPreview.length} Products Detected)
                </span>
                {parsedPreview.length > 0 && (
                  <span className="badge bg-success small px-2 py-1">Ready to Import</span>
                )}
              </div>

              <div
                className="card-body p-3 flex-grow-1"
                style={{ maxHeight: '440px', overflowY: 'auto' }}
              >
                {parsedPreview.length === 0 ? (
                  <div className="text-center py-5 text-muted">
                    <i className="fas fa-boxes fa-3x mb-3 text-secondary opacity-50" />
                    <p className="small m-0 fw-bold text-secondary">
                      No products detected yet.
                    </p>
                    <p className="text-muted" style={{ fontSize: '0.78rem' }}>
                      Paste JSON on the left, load the sample template, or copy the Gemini prompt to generate products.
                    </p>
                    <button
                      type="button"
                      onClick={handleLoadSample}
                      className="btn btn-outline-primary btn-sm px-3 mt-2"
                    >
                      <i className="fas fa-magic me-1" /> Insert Sample Products
                    </button>
                  </div>
                ) : (
                  <div className="list-group list-group-flush">
                    {parsedPreview.map((item, idx) => (
                      <div key={idx} className="list-group-item px-0 py-2.5 border-bottom">
                        <div className="d-flex justify-content-between align-items-start gap-2">
                          <div style={{ flex: 1, minWidth: 0 }}>
                            <div className="d-flex align-items-center gap-1.5 mb-1 flex-wrap">
                              <span className="badge bg-secondary text-light" style={{ fontSize: '0.65rem' }}>
                                #{idx + 1}
                              </span>
                              <strong className="text-dark small text-truncate d-block" style={{ maxWidth: '280px' }}>
                                {item.name || 'Untitled Product'}
                              </strong>
                            </div>
                            <div className="text-muted" style={{ fontSize: '0.74rem' }}>
                              Category:{' '}
                              <span className="text-primary fw-bold">
                                {item.category || 'General'}
                                {item.subcategory ? ` ➔ ${item.subcategory}` : ''}
                              </span>{' '}
                              | Stock: <span className="fw-semibold">{item.stock || 25}</span>
                            </div>
                            {item.seoTitle && (
                              <div className="text-muted text-truncate" style={{ fontSize: '0.7rem' }}>
                                SEO: <span className="text-success">{item.seoTitle}</span>
                              </div>
                            )}
                          </div>
                          <div className="text-end flex-shrink-0">
                            <span
                              className="fw-bold d-block"
                              style={{ fontSize: '0.9rem', color: 'var(--pd-primary, #ea580c)' }}
                            >
                              Rs. {Number(item.price || 0).toLocaleString()}
                            </span>
                            {item.originalPrice && (
                              <del className="text-muted" style={{ fontSize: '0.74rem' }}>
                                Rs. {Number(item.originalPrice).toLocaleString()}
                              </del>
                            )}
                          </div>
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </div>

              {/* Status Message */}
              {importResult && (
                <div
                  className={`p-3 border-top ${
                    importResult.success ? 'bg-success text-white' : 'bg-danger text-white'
                  }`}
                >
                  <div className="d-flex align-items-center justify-content-between gap-2">
                    <span className="small fw-bold">
                      {importResult.success
                        ? `🎉 ${importResult.message}`
                        : `❌ ${importResult.error}`}
                    </span>
                    {importResult.success && (
                      <button
                        onClick={() => router.push('/admin/products')}
                        className="btn btn-light btn-sm fw-bold px-3 flex-shrink-0"
                      >
                        View in Catalog ➔
                      </button>
                    )}
                  </div>
                </div>
              )}

              {/* Footer CTA */}
              <div className="card-footer bg-white p-3 border-top">
                <button
                  type="button"
                  onClick={handleExecuteImport}
                  disabled={parsedPreview.length === 0 || importing || !!parseError}
                  className="btn w-100 py-2.5 fw-bold d-flex align-items-center justify-content-center gap-2 shadow-sm text-white"
                  style={{
                    background:
                      parsedPreview.length > 0 && !parseError
                        ? '#16a34a'
                        : '#94a3b8',
                    border: 'none',
                    borderRadius: '8px',
                  }}
                >
                  {importing ? (
                    <>
                      <span
                        className="spinner-border spinner-border-sm"
                        role="status"
                        aria-hidden="true"
                      />
                      Importing Products to Database...
                    </>
                  ) : (
                    <>
                      <i className="fas fa-cloud-upload-alt" />
                      Import {parsedPreview.length} Products to Store
                    </>
                  )}
                </button>
              </div>
            </div>
          </div>
        </div>

        {/* ── Gemini Prompt & Schema Modal ── */}
        {aiPromptModalOpen && (
          <div
            style={{
              position: 'fixed',
              inset: 0,
              zIndex: 99999,
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              background: 'rgba(15, 23, 42, 0.7)',
              backdropFilter: 'blur(6px)',
              padding: '16px',
            }}
          >
            <div
              className="card border-0 shadow-lg rounded-3"
              style={{
                width: '100%',
                maxWidth: '850px',
                maxHeight: '90vh',
                display: 'flex',
                flexDirection: 'column',
                background: '#ffffff',
                overflow: 'hidden',
              }}
            >
              {/* Modal Header */}
              <div className="card-header bg-dark text-white py-3 px-4 d-flex align-items-center justify-content-between">
                <div className="d-flex align-items-center gap-2">
                  <span
                    className="p-1.5 rounded-circle bg-primary text-white d-flex align-items-center justify-content-center"
                    style={{ width: '28px', height: '28px', fontSize: '13px' }}
                  >
                    <i className="fas fa-robot" />
                  </span>
                  <strong style={{ fontSize: '1.05rem' }}>Gemini AI Prompt & Category Blueprint</strong>
                </div>
                <button
                  type="button"
                  onClick={() => setAiPromptModalOpen(false)}
                  className="btn-close btn-close-white"
                  aria-label="Close"
                />
              </div>

              {/* Modal Body with Tabs / Sections */}
              <div className="card-body p-4" style={{ overflowY: 'auto', flex: '1 1 auto' }}>
                <div className="alert alert-info py-2.5 px-3 small mb-3 d-flex align-items-start gap-2">
                  <i className="fas fa-info-circle text-primary mt-0.5 flex-shrink-0" />
                  <div>
                    <strong>Live Category Synchronization:</strong> The prompt below is dynamically populated with all{' '}
                    <strong>{categories.length} categories and subcategories</strong> currently active in your database. When you give product details to Gemini, it will automatically match them to these categories!
                  </div>
                </div>

                {/* Section 1: Copy-Paste Full Prompt */}
                <div className="mb-4">
                  <div className="d-flex align-items-center justify-content-between mb-2">
                    <label className="fw-bold text-dark small m-0">
                      1. Complete Gemini Prompt (Copy & Paste directly into Gemini / ChatGPT):
                    </label>
                    <button
                      type="button"
                      onClick={handleCopyPrompt}
                      className={`btn btn-sm fw-bold px-3 ${
                        copiedPrompt ? 'btn-success text-white' : 'btn-primary text-white'
                      }`}
                      style={{
                        background: copiedPrompt
                          ? '#16a34a'
                          : 'var(--pd-primary, #ea580c)',
                        border: 'none',
                      }}
                    >
                      <i className={copiedPrompt ? 'fas fa-check me-1' : 'fas fa-copy me-1'} />
                      {copiedPrompt ? '✓ Copied to Clipboard!' : 'Copy Full Prompt'}
                    </button>
                  </div>
                  <pre
                    className="p-3 rounded-2 text-white font-monospace small m-0"
                    style={{
                      background: '#0f172a',
                      color: '#38bdf8',
                      maxHeight: '220px',
                      overflowY: 'auto',
                      whiteSpace: 'pre-wrap',
                      fontSize: '0.78rem',
                      lineHeight: '1.45',
                    }}
                  >
                    {fullGeminiPromptText}
                  </pre>
                </div>

                {/* Section 2: Live Categories Tree */}
                <div className="mb-4">
                  <div className="d-flex align-items-center justify-content-between mb-2">
                    <label className="fw-bold text-dark small m-0">
                      2. Live Categories & Subcategories ({categories.length} Active in Database):
                    </label>
                  </div>
                  <div
                    className="p-3 rounded-2 bg-light border font-monospace small"
                    style={{
                      maxHeight: '150px',
                      overflowY: 'auto',
                      fontSize: '0.78rem',
                      lineHeight: '1.4',
                      color: '#1e293b',
                    }}
                  >
                    <pre className="m-0" style={{ whiteSpace: 'pre-wrap', fontFamily: 'inherit' }}>
                      {dynamicTaxonomyText}
                    </pre>
                  </div>
                </div>

                {/* Section 3: Clean Sample JSON Format */}
                <div>
                  <div className="d-flex align-items-center justify-content-between mb-2">
                    <label className="fw-bold text-dark small m-0">
                      3. Expected JSON Schema Output (High SEO & Rich Specs):
                    </label>
                    <div className="d-flex gap-2">
                      <button
                        type="button"
                        onClick={handleCopyJson}
                        className="btn btn-outline-secondary btn-sm fw-bold px-2.5"
                      >
                        <i className={copiedJson ? 'fas fa-check me-1' : 'fas fa-copy me-1'} />
                        {copiedJson ? '✓ Copied JSON' : 'Copy JSON'}
                      </button>
                      <button
                        type="button"
                        onClick={handleLoadAiTemplateIntoEditor}
                        className="btn btn-outline-primary btn-sm fw-bold px-2.5"
                      >
                        <i className="fas fa-file-import me-1" /> Insert in Editor
                      </button>
                    </div>
                  </div>
                  <pre
                    className="p-3 rounded-2 text-white font-monospace small m-0"
                    style={{
                      background: '#1e293b',
                      color: '#a7f3d0',
                      maxHeight: '180px',
                      overflowY: 'auto',
                      fontSize: '0.76rem',
                    }}
                  >
                    {dynamicSampleJsonText}
                  </pre>
                </div>
              </div>

              {/* Modal Footer */}
              <div className="card-footer bg-white py-3 px-4 border-top d-flex justify-content-between align-items-center">
                <span className="text-muted small">
                  💡 Tip: You can paste multiple product photos at once in Gemini with this prompt!
                </span>
                <button
                  type="button"
                  onClick={() => setAiPromptModalOpen(false)}
                  className="btn btn-dark btn-sm px-4 fw-bold"
                >
                  Close
                </button>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
